image:
  file: .gitpod.dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false
    addLabel: false
tasks:
  - command: |
      export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$PATH
      cd /workspace/tutor-app/flutter
      flutter pub get
      cd ..
      cd ./server
      npm i
      npm start

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - aaron-bond.better-comments
