image:
  file: .gitpod.dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false
    addLabel: false
tasks:
  - command: |
      export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$HOME/flutter/.pub-cache/bin:$PATH
      cd /workspace/tutor-app/flutter
      flutter pub get
      npm i -g firebase-tools
      flutter pub global activate flutterfire_cli

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - aaron-bond.better-comments
