// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTEtrLtELHlU7DDrAFtzJCFE5nvKF1I0',
    appId: '1:631895189358:web:b30edbd97fe9d1c020037f',
    messagingSenderId: '631895189358',
    projectId: 'tutor-app-1a9ff',
    authDomain: 'tutor-app-1a9ff.firebaseapp.com',
    storageBucket: 'tutor-app-1a9ff.appspot.com',
    measurementId: 'G-KL679TJB48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4crIi-VZSLp4LKsbGPsaHz5UFvgN6-IE',
    appId: '1:631895189358:android:5418ef9135c93a3c20037f',
    messagingSenderId: '631895189358',
    projectId: 'tutor-app-1a9ff',
    storageBucket: 'tutor-app-1a9ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShVewQY10KRbCtv0cgPOLQO4887AUyf8',
    appId: '1:631895189358:ios:046671b6540c715620037f',
    messagingSenderId: '631895189358',
    projectId: 'tutor-app-1a9ff',
    storageBucket: 'tutor-app-1a9ff.appspot.com',
    iosClientId: '631895189358-1a97tmub0f999vifkkscehrs9bl7s1pc.apps.googleusercontent.com',
    iosBundleId: 'com.samh.tutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKbh-q1YVaOPZllHdPq6g6ntg7Fsl6BhE',
    appId: '1:631895189358:ios:2dd4b637d0cc886320037f',
    messagingSenderId: '631895189358',
    projectId: 'tutor-app-1a9ff',
    storageBucket: 'tutor-app-1a9ff.appspot.com',
    iosClientId: '631895189358-df16ara7mki0s9qqtdjo31ti1slrfghh.apps.googleusercontent.com',
    iosBundleId: 'com.samh.tutorAppMacOS',
  );
}
